"""First-wall quantum/classical audit for the same reduced Bianchi IX Hamiltonian.

The classical reduced generator for s=-alpha is -sqrt(p_+^2+p_-^2+W).
Here we choose the direct positive-square-root operator ordering
G(s)=-sqrt(-hbar^2 Delta + W(s,beta)) on a finite Dirichlet box.
This is one quantization choice, not a unique quantum-gravity prescription.
The potential cap is a numerical regulator; accepted results require tiny
probability in the capped and boundary regions and cap/grid sensitivity tests.
"""
from __future__ import annotations
from dataclasses import dataclass
import numpy as np
from scipy.linalg import eigh_tridiagonal
from scipy.stats import qmc, norm

SQ3=np.sqrt(3.0)

def wall_grid(s,bp,bm):
    A=-4*s-8*bp
    Bp=-4*s+4*bp+4*SQ3*bm; Bm=-4*s+4*bp-4*SQ3*bm
    B0=-4*s+4*bp
    C1=-4*s-2*bp+2*SQ3*bm; C2=-4*s-2*bp-2*SQ3*bm
    eA,eBp,eBm,eB0,eC1,eC2=[np.exp(np.clip(z,-745.,700.)) for z in (A,Bp,Bm,B0,C1,C2)]
    return (eA+eBp+eBm-2*eB0-2*eC1-2*eC2)/3.0

@dataclass(frozen=True)
class PacketSpec:
    hbar: float=.2
    sigma: float=.3
    beta_plus: float=0.
    beta_minus: float=0.
    p_plus: float=1.
    p_minus: float=.31

class QuantumBianchiIX:
    def __init__(self,hbar=.2,bp_bounds=(-5.,5.),bm_bounds=(-8.,5.),nx=100,ny=130,potential_cap=30.):
        if hbar<=0 or nx<20 or ny<20 or potential_cap<=0: raise ValueError('invalid grid parameters')
        self.hbar=float(hbar);self.bp_bounds=tuple(map(float,bp_bounds));self.bm_bounds=tuple(map(float,bm_bounds));self.nx=int(nx);self.ny=int(ny);self.cap=float(potential_cap)
        self.bp=np.linspace(*self.bp_bounds,self.nx+2)[1:-1];self.bm=np.linspace(*self.bm_bounds,self.ny+2)[1:-1]
        self.dx=float(self.bp[1]-self.bp[0]);self.dy=float(self.bm[1]-self.bm[0])
        self.BP,self.BM=np.meshgrid(self.bp,self.bm,indexing='ij')
    def initial(self,p:PacketSpec):
        if not np.isclose(p.hbar,self.hbar): raise ValueError('packet/grid hbar mismatch')
        z=(self.BP-p.beta_plus)**2+(self.BM-p.beta_minus)**2
        phase=(p.p_plus*(self.BP-p.beta_plus)+p.p_minus*(self.BM-p.beta_minus))/p.hbar
        v=np.exp(-z/(4*p.sigma**2)+1j*phase).ravel();v/=np.linalg.norm(v);return v
    def apply_A(self,v,s):
        q=np.asarray(v).reshape(self.nx,self.ny)
        lap=2*q/self.dx**2+2*q/self.dy**2
        lap[:-1]-=q[1:]/self.dx**2;lap[1:]-=q[:-1]/self.dx**2
        lap[:,:-1]-=q[:,1:]/self.dy**2;lap[:,1:]-=q[:,:-1]/self.dy**2
        W=np.minimum(wall_grid(s,self.BP,self.BM),self.cap)
        return (self.hbar**2*lap+W*q).ravel()
    def step(self,v,s_mid,ds,krylov_dim=48):
        """Midpoint frozen-H propagator exp(+i ds sqrt(A)/hbar) via Lanczos.

        The plus sign gives the classical s-flow generated by -sqrt(A)'s symbol.
        A three-term Hermitian Lanczos recurrence is used. Convergence is audited
        by increasing krylov_dim; no per-step renormalization is applied.
        """
        v=np.asarray(v,complex);beta=np.linalg.norm(v);q=v/beta;qprev=np.zeros_like(q);bprev=0.;Q=[];aa=[];bb=[]
        for j in range(int(krylov_dim)):
            Q.append(q.copy());w=self.apply_A(q,s_mid);a=float(np.vdot(q,w).real);w-=a*q+bprev*qprev;aa.append(a)
            if j==krylov_dim-1: break
            b=float(np.linalg.norm(w));bb.append(b)
            if b<1e-13: break
            qprev,q=q,w/b;bprev=b
        Q=np.asarray(Q);aa=np.asarray(aa);bb=np.asarray(bb[:len(aa)-1]);ev,U=eigh_tridiagonal(aa,bb)
        if ev.min() < -1e-8: raise RuntimeError(f'negative Ritz value {ev.min()}')
        coeff=U@(np.exp(1j*ds*np.sqrt(np.maximum(ev,0))/self.hbar)*U[0])
        return beta*(coeff@Q),float(ev.min())
    def observables(self,v,s):
        prob=abs(np.asarray(v).reshape(self.nx,self.ny))**2
        mx=float(np.sum(prob*self.BP));my=float(np.sum(prob*self.BM));dx=self.BP-mx;dy=self.BM-my
        cov=np.array([[np.sum(prob*dx*dx),np.sum(prob*dx*dy)],[np.sum(prob*dx*dy),np.sum(prob*dy*dy)]],float)
        eig=np.linalg.eigvalsh(cov);W=wall_grid(s,self.BP,self.BM)
        edge=(self.BP<self.bp[0]+.5)|(self.BP>self.bp[-1]-.5)|(self.BM<self.bm[0]+.5)|(self.BM>self.bm[-1]-.5)
        mask=prob>0;entropy=float(-np.sum(prob[mask]*np.log(prob[mask])))
        return {'mean':[mx,my],'covariance':cov.tolist(),'cov_eigenvalues':eig.tolist(),
                'rms_width':float(np.sqrt(np.trace(cov))),'norm':float(prob.sum()),
                'edge_mass':float(prob[edge].sum()),'capped_region_mass':float(prob[W>self.cap/2].sum()),
                'shannon_grid_entropy':entropy,'inverse_participation':float(np.sum(prob*prob))}

def propagate_quantum(model,packet,s0=2.,s1=6.,ds=.05,krylov_dim=48,save_times=(2.,4.,4.6,5.,6.),keep_density=False):
    save_times=np.asarray(save_times,float)
    if save_times[0]<s0-1e-12 or save_times[-1]>s1+1e-12: raise ValueError('save times outside interval')
    n=int(round((s1-s0)/ds));ds=(s1-s0)/n;v=model.initial(packet);s=float(s0);rows=[];dens={}
    def record(t):
        rows.append({'s':float(t),**model.observables(v,t)})
        if keep_density: dens[str(float(t))]=abs(v.reshape(model.nx,model.ny))**2
    idx=0
    if abs(save_times[0]-s0)<1e-10: record(s0);idx=1
    min_ritz=np.inf
    for _ in range(n):
        v,r=model.step(v,s+ds/2,ds,krylov_dim);min_ritz=min(min_ritz,r);s+=ds
        while idx<len(save_times) and s>=save_times[idx]-ds/2:
            record(float(save_times[idx]));idx+=1
    return {'rows':rows,'final_state':v,'densities':dens,'min_ritz':float(min_ritz),'ds':float(ds)}

def _wall_vec(s,bp,bm):
    A=-4*s-8*bp;Bp=-4*s+4*bp+4*SQ3*bm;Bm=-4*s+4*bp-4*SQ3*bm;B0=-4*s+4*bp;C1=-4*s-2*bp+2*SQ3*bm;C2=-4*s-2*bp-2*SQ3*bm
    eA,eBp,eBm,eB0,eC1,eC2=[np.exp(np.clip(z,-745.,700.)) for z in (A,Bp,Bm,B0,C1,C2)]
    W=(eA+eBp+eBm-2*eB0-2*eC1-2*eC2)/3
    gp=(-8*eA+4*eBp+4*eBm-8*eB0+4*eC1+4*eC2)/3
    gm=(4*SQ3*(eBp-eBm)-4*SQ3*(eC1-eC2))/3
    return W,gp,gm

def _rhs_vec(s,Y):
    bp,bm,pp,pm=Y;W,gp,gm=_wall_vec(s,bp,bm);rad=pp*pp+pm*pm+W
    if np.any(rad<=0): raise RuntimeError('classical ensemble left positive reduced branch')
    H=np.sqrt(rad);return np.array([-pp/H,-pm/H,.5*gp/H,.5*gm/H])

def initial_wigner_ensemble(packet:PacketSpec,n=4096,seed=20260917):
    m=int(round(np.log2(n)))
    if 2**m!=n: raise ValueError('Sobol sample count must be power of two')
    u=qmc.Sobol(d=4,scramble=True,seed=seed).random_base2(m);z=norm.ppf(np.clip(u,1e-14,1-1e-14));sp=packet.hbar/(2*packet.sigma)
    Y=np.empty((4,n));Y[0]=packet.beta_plus+packet.sigma*z[:,0];Y[1]=packet.beta_minus+packet.sigma*z[:,1];Y[2]=packet.p_plus+sp*z[:,2];Y[3]=packet.p_minus+sp*z[:,3];return Y

def propagate_classical_ensemble(packet:PacketSpec,s0=2.,s1=6.,ds=.004,save_times=(2.,4.,4.6,5.,6.),n=4096,seed=20260917):
    Y=initial_wigner_ensemble(packet,n,seed);save_times=np.asarray(save_times,float);rows=[];s=float(s0);idx=0
    def rec(t):
        xy=Y[:2];mean=xy.mean(1);cov=np.cov(xy);rows.append({'s':float(t),'mean':mean.tolist(),'covariance':cov.tolist(),'cov_eigenvalues':np.linalg.eigvalsh(cov).tolist(),'rms_width':float(np.sqrt(np.trace(cov)))})
    if abs(save_times[0]-s0)<1e-10:rec(s0);idx=1
    steps=int(round((s1-s0)/ds));ds=(s1-s0)/steps
    for _ in range(steps):
        k1=_rhs_vec(s,Y);k2=_rhs_vec(s+ds/2,Y+ds*k1/2);k3=_rhs_vec(s+ds/2,Y+ds*k2/2);k4=_rhs_vec(s+ds,Y+ds*k3);Y+=ds*(k1+2*k2+2*k3+k4)/6;s+=ds
        while idx<len(save_times) and s>=save_times[idx]-ds/2:rec(float(save_times[idx]));idx+=1
    return {'rows':rows,'final':Y,'ds':float(ds),'n':int(n),'seed':int(seed)}
